### ISSUE TITLE
SOS区块后面应该是跟了2bytes的长度？

### ISSUE THREAD

**Issue by xinlin-z** [MROS/jpeg_tutorial#6]
如题，我通过读取SOS区块的内容发现的，这个长度刚好是不包含mcu内容的头的长度，包括2个bytes的长度字段。

你的教程没有这2个bytes的说明，对吗？

**Comment by MROS** [comment]
https://github.com/MROS/jpeg_tutorial/blob/master/doc/%E8%B7%9F%E6%88%91%E5%AF%ABjpeg%E8%A7%A3%E7%A2%BC%E5%99%A8%EF%BC%88%E4%BA%8C%EF%BC%89%E6%AA%94%E6%A1%88%E7%B5%90%E6%A7%8B.md#%E6%89%80%E6%9C%89%E5%8D%80%E6%AE%B5%E5%85%B1%E9%80%9A%E7%9A%84%E7%B5%90%E6%A7%8B

這一段有說明到長度字段，請問是你需要的嗎?
