### ISSUE TITLE
I need help of decode raw data from jpeg

### ISSUE THREAD

**Issue by HanalogInstruments** [MROS/jpeg_tutorial#7]
Hi,

I have some jpeg encrypted 153605 bytes from the header so only raw data without SOI-SOS

Could you help me to decode the raw data from this jpeg to get demension of jpeg? And get jpeg header ?

Also i want to know how to do it

***Sample:***

https://drive.google.com/file/d/1emXcVGL3dWm7-ctVQT9by4_6Uie0MkzX/view?usp=drivesdk

Files I use (IMG_1333*) have standard tables - Huffman tables from JPEG standard and quantization tables for max quality (all "1").
But i need to fix information in SOF:
- MCU layout (DataUnit per MCU) -> done ( s2x1.jpg ) ( same chroma sampling 4:2:2 )
- Image dimensions -> i need you help to decode raw data to get width and height

https://drive.google.com/drive/folders/1Ylc61SRLVCjZ2nSla7e-8xmfg95EyMuu

***Note:***

- use S2x1.jpg file as good header cut from SOI -> FFDA + 12 bytes
- cut 0-153605 bytes ( dec ) of .jpg.nppp or jpg.wiot and merger it to the good header s2x1
- because width and height from good header diffrence than the raw data from corrupted .jpg.* so we need to decode raw data and get width and height

Best Regards
Hanalog Inc.

**Comment by MROS** [comment]
Sorry, I think solving this problem can't make the tutorial better.
